### ISSUE TITLE
compatibility with coolprop (and teqp) JSON format

### ISSUE THREAD

**Issue by longemen3000** [ClapeyronThermo/Clapeyron.jl#110]
the Coolprop JSON has a lot of additional info that we currently don't use. other than that, it would require another dependency. but seems cool to instantiate and compare implementations (and methods)

**Comment by ianhbell** [comment]
And the CoolProp JSON format is used in teqp too, so that would help with interoperability

**Comment by ianhbell** [comment]
Sorry, just noticed you mention teqp in the issue title too. Oops.
