### ISSUE TITLE
tcPR, tcRK and families

### ISSUE THREAD

**Issue by longemen3000** [ClapeyronThermo/Clapeyron.jl#126]
it would be useful to have the translated and consistent PR and RK cubics. there is also a version with advanced mixing rules and their own set of parameters for van laar, UNIQUAC, NRTL and Wilson
https://pubs.acs.org/doi/10.1021/acs.iecr.1c03003

**Comment by ianhbell** [comment]
You might want to implement these parameters, at least optionally: https://pubs.acs.org/doi/abs/10.1021/acs.jced.7b00967
