### ISSUE TITLE
Accessing and modifying model parameters via REPL - SAFTgammaMie

### ISSUE THREAD

**Issue by michelevalsecchi** [ClapeyronThermo/Clapeyron.jl#145]
Hi, I have been accessing and modifying the parameters of a water/PEG model (model = SAFTgammaMie(["water","PEG_1sit"])) in Clapeyron directly via the Julia REPL by using the "model.vrmodel.params" and "model.params" attributes. However, I have noticed that when there are many association sites the "model.vrmodel.params.epsilon_assoc.values" and "model.params.epsilon_assoc.values" vectors (same for bondvol) contain a different number of entries. In particular, it seems that the vrmodel one is missing some association values. Does this impact the calculations at all?

On another note, I have been trying to modify the parameters and was wondering if changing both the entries in "model.vrmodel.params" and "model.params" (accounting for symmetry) is sufficient to temporarily update a given parameter. 

Thanks in advance for the help!

**Comment by longemen3000** [comment]
Hi, if you are updating directly the values on the REPL, the ones actually used in the calculation are the ones in `model.vrmodel.params.epsilon_assoc`. The long answer is that, because the association solver only takes component-based site pairs, we do a transformation from group-based sites to component-based sites, and those are stored in `vrmodel`. 

> On another note, I have been trying to modify the parameters and was wondering if changing both the entries in "model.vrmodel.params" and "model.params" (accounting for symmetry) is sufficient to temporarily update a given parameter.
If you don't modify the number of groups or sites, and in this particular case that is correct. we have something of a general function, `recombine!` that recalculates every needed value (including association parameters, parameter caches, etc) from some starting parameters (In this particular case, the original parameters are the group-based ones and the calculated ones are in `model.vrmodel`. UNIFAC also has a cache that is recalculated when `recombine!` is called.)


By the way, you can modify directly the pair parameters and symmetry is respected:
```
julia> param = PairParam("sym",["1","2"],rand(2,2))
2×2 PairParam{Float64}(["1", "2"]) with values:
 0.576906  0.517533
 0.818169  0.981202

julia> param[1,2] = 100 #setting a non-diagonal value i.j will also set j,i, you can op out of this by calling setindex!(param,val,i,j,false)
100

julia> param
2×2 PairParam{Float64}(["1", "2"]) with values:
   0.576906  100.0
 100.0         0.981202
```

**Comment by michelevalsecchi** [comment]
Thanks for the quick answer! I have been trying recombine! and it works as expected, thanks! Regarding the different number of entries, I am assuming the reason might be that PEG is heteronuclear and has two associating groups. See the attached screenshots for reference.

![bondvol](https://user-images.githubusercontent.com/43810602/222404924-888e0f0a-4c4d-42fc-9bcd-82de3d4dadcf.PNG)
![epsilon_assoc](https://user-images.githubusercontent.com/43810602/222404930-3f1457d4-315b-4c07-b8ad-5a33ad519d0b.PNG)

**Comment by michelevalsecchi** [comment]
Notably also the dispersion is modified. The numbers don't even always match in the two sets in this case. Is this due to the transformation you mentioned?

![epsilon](https://user-images.githubusercontent.com/43810602/222407716-f5bbfd06-d10f-437a-8f36-7b83f597662e.PNG)

**Comment by michelevalsecchi** [comment]
Here they are. As you suspected, it seems that the model.sites is not counting the PEG sites properly. It's pretty interesting however that the error here is on model, not model.vrmodel

![sites](https://user-images.githubusercontent.com/43810602/222454762-57a0471d-eff2-4364-acbb-7b9661958bf4.PNG)

**Comment by longemen3000** [comment]
ok, i can reproduce your bug. reproducer:

```
like_data = """
Clapeyron Database File
SAFTgammaMie Like Parameters [csvtype = like,grouptype = SAFTgammaMie]
species,vst,S,lambda_r,lambda_a,sigma,epsilon,n_H,n_e1,n_e2,Mw
CH2_PEO,1,1,12,6,4,300,0,0,0,100
cO_1sit,1,1,12,6,4,300,0,0,0,100
"""

mw_data = """
Clapeyron Database File
SAFTgammaMie Like Parameters
species,Mw
CH2_PEO,100
cO_1sit,100
"""

assoc_data = """
Clapeyron Database File,,,,,,
SAFTgammaMie Assoc Parameters [csvtype = assoc,grouptype = SAFTgammaMie]
species1,site1,species2,site2,epsilon_assoc,bondvol,source
H2O,H,cO_1sit,e1,2193.2,5e-29,
CH2OH,H,cO_1sit,e1,1572.5,4.331e-28,
"""

group_data = """
Clapeyron Database File,
SAFTgammaMie Groups [csvtype = groups,grouptype = SAFTgammaMie]
species,groups
PEG_1sit,"[""CH2_PEO"" => 2000,""cO_1sit"" => 1000,""CH2OH"" => 2]"
"""

model = SAFTgammaMie(["water","PEG_1sit"],userlocations = [like_data,assoc_data,mw_data],group_userlocations = [group_data])
```

**Comment by michelevalsecchi** [comment]
Great, thanks for the time! Do you think this affects calculations / is it hard to fix?

PS: I was using recombine! and I notice that interaction parameters that  are calculated by default using combining rules (i.e. no entry in the databanks) are reset even if their value is set via model.params. This does not happen for the ones that have an entry. Is this behaviour intended?

**Comment by longemen3000** [comment]
I plan to get a new release today with the fix.
>interaction parameters calculated by default using combining rules (i.e. no entry in the databanks) are reset even if their value is set via model.params. This does not happen for the ones that have an entry. Is this behaviour intended?

Yes, we have a boolean flag for values that are not set in `params.param.ismissingvalues`. if that is false, then the value shouldn't be touched during recombine

**Comment by michelevalsecchi** [comment]
OK fantastic! I'll try the new version ASAP and play with the boolean flag. Thanks a lot for the support!
