### ISSUE TITLE
Wrong DOI for SAFTVRMIE

### ISSUE THREAD

**Issue by ianhbell** [ClapeyronThermo/Clapeyron.jl#146]
In the file ``database/SAFT/SAFTVRMie)/SAFTVRMie_like.csv``, the first row is correct from Lafitte, and the subsequent rows increment by 1, but they should all be 10.1063/1.4819786

**Comment by pw0908** [comment]
Whoops, that's a silly mistake. We should probably check the other eos...

**Comment by ianhbell** [comment]
I checked, and it seems that is the only SAFT model where DOI were provided in the source column

**Comment by ianhbell** [comment]
Closed by 7be3a8e
