### ISSUE TITLE
Ordered results for DETPFlash

### ISSUE THREAD

**Issue by Isaac-Severinsen** [ClapeyronThermo/Clapeyron.jl#151]
Hi,

Novice Julia user so forgive any syntax errors.
I was trying one of the examples for CO2 and water using PR (although the issue persists with different EOS).
I wrapped it with a for loop and noticed that the results are not in a consistent order?

in the MWE below, x_3PC is not always in the order:
[x_H2O x_CO2; y_H2O y_CO2]
It seems to switch to:
[y_H2O y_CO2; x_H2O x_CO2]
seemingly at random.

MWE:

```
using Clapeyron
using BlackBoxOptim

system3PCSAFT = PR(["water", "carbon dioxide"])
N = 10
co2_liq = Array{Float64}(undef, N)
co2_gas = Array{Float64}(undef, N)

for i in range(1,N)
    print(i)
    T = 25.0 + 273.15 + float(i)*1.0
    p = 101.3e5
    n = [1.0, 1.0]
    method = DETPFlash()

    (x_3PC, nvals_3PC, G_3PC) = tp_flash(system3PCSAFT, p, T, n, method)

    print(x_3PC)
    print("\n")

    co2_liq[i] = x_3PC[1,1]
    co2_gas[i] = x_3PC[2,1]

end
```

Output:
1[0.01184230440216988 0.9881576955978301; 0.9957107587108236 0.0042892412891765005]
2[0.011851147486081388 0.9881488525139186; 0.9956258331262761 0.0043741668737239565]
3[0.011849546195068367 0.9881504538049316; 0.9955402081550339 0.004459791844966114]
4[0.011836709378417873 0.9881632906215821; 0.9954539106685774 0.004546089331422654]
5[0.9953669842321345 0.004633015767865578; 0.011811759180824404 0.9881882408191758]
6[0.011773764098992718 0.9882262359010071; 0.9952794653301794 0.00472053466982063]
7[0.011721679578621585 0.9882783204213784; 0.9951914063405946 0.004808593659405448]
8[0.011654383783419245 0.9883456162165807; 0.9951028464558163 0.004897153544183698]
9[0.995013855682472 0.004986144317528056; 0.01157064222153387 0.988429357778466]
10[0.9949244879537427 0.005075512046257263; 0.01146911605682136 0.9885308839431786]

**Comment by longemen3000** [comment]
hmm, that is, in fact, an implementation problem on `DETPFlash`. maybe you could try `MichelsenTPFlash` instead?. `DETPFlash` is the most naive TP-flash algorithm possible, so while it finds minima, it doesn't assure any order. `MichelsenTPFlash` on the other part has a defined vapor and liquid phase, so it is always the same order

**Comment by longemen3000** [comment]
this should be fixed by https://github.com/ClapeyronThermo/Clapeyron.jl/commit/329818d5c1be95d0ae953e0dc92097ed01685575

**Comment by Isaac-Severinsen** [comment]
Awesome thanks :) Will give it a go shortly.

**Comment by Isaac-Severinsen** [comment]
Have tried it and it works great now, thanks :)
