### ISSUE TITLE
EoS: ePC-SAFT

### ISSUE THREAD

**Issue by moesphere** [ClapeyronThermo/Clapeyron.jl#158]
It would be great to implement PC-SAFT for electrolytes. [Original paper](http://dx.doi.org/10.1021/ie0488142) and [revision of ePC-SAFT](http://dx.doi.org/10.1016/j.cherd.2014.05.017).

A combination with the already implemented pharmaPCSAFT model would be benificial likewise.

**Comment by longemen3000** [comment]
There is actually an implementation of ePCSAFT, in the `EectrolyteModels` branch:
https://github.com/ClapeyronThermo/Clapeyron.jl/blob/ElectrolyteModels/src/models/SAFT/PCSAFT/variants/ePCSAFT.jl
We are still looking on how to treat electrolytes in general

**Comment by moesphere** [comment]
Thanks for the hint to the `ElectrolyteModels` branch. To me, it seems that the implemented `ePCSAFT` model does not consider electrolytes. The reference to the corresponding article does not mention electrolytes. In the implementation of Cameretti, Sadowski, and Mollerup, (see original paper link in [my comment above](https://github.com/ClapeyronThermo/Clapeyron.jl/issues/158#issue-1643713250)), an additional term for ions to the residual Helmholtz energy is added.

**Comment by longemen3000** [comment]
hmm, weird, I remember seeing some terms in ePCSAFT, maybe it got deleted?

**Comment by moesphere** [comment]
Found it. Coupling `pharmaPCSAFT` with `DH` would mean to create a new model with a new parameter as there is not yet a way to treat electrolytes in general, as you mentioned above, correct?

**Comment by longemen3000** [comment]
yes, ideally, that would be via the `ElectrolyteSAFT` wrapper

**Comment by pw0908** [comment]
Yep!
