### ISSUE TITLE
bug in SAFT-VR SW?

### ISSUE THREAD

**Issue by TermeHansen** [ClapeyronThermo/Clapeyron.jl#165]
Just started to look around in this very nice module - great work!

As a first I have tried to reproduce the Cp of CO2 plot from the frontpage. 
![image](https://raw.githubusercontent.com/ClapeyronThermo/Clapeyron.jl/master/docs/CO2_cp.svg)

using:
```
compounds = ["carbon dioxide"]

model1 = SRK(compounds; idealmodel=ReidIdeal)
model2 = GERG2008(compounds)
model3 = SAFTVRSW(compounds; idealmodel=ReidIdeal);
model4 = PCSAFT(compounds; idealmodel=ReidIdeal);
model5 = SAFTVRMie(compounds; idealmodel=ReidIdeal);
```

I get:
![image](https://user-images.githubusercontent.com/6922018/230398326-659871f3-3c6b-491e-aae5-d608890c0b93.png)

Which seems fine except for the `SAFT-VR SW`. Any pointers to why I see that difference to your plot?

**Comment by longemen3000** [comment]
on a preliminary testing, `SAFTVRSW` seems consistent:
```
#tests that the gibbs energy and chemical potential have the same values. the first number is the difference
julia> Clapeyron.gibbs_duhem(model3,0.03,300.) 
(0.0, 11561.822765804463, 11561.822765804463)

#test that the ideal model returns an ideal pressure,the result is the difference of pressures
julia> Clapeyron.ideal_consistency(model3,0.03,300.)
0.0
```
so, if any bugs present, seems to be a subtle one

**Comment by pw0908** [comment]
It's been a while since I made that figure but, based on the figure we used in our paper, it seems like we removed SAFT-VR SW from it. I believe that may have been because the results had changed to something like TermeHansen is showing. Ill quickly benchmark SAFT-VR SW to the original paper and see if we can still replicate their results.

**Comment by pw0908** [comment]
I've now done the benchmark and can confirm that the current implementation of SAFT-VR SW replicates the original papers. There must have been something wrong at the time with the code.

**Comment by TermeHansen** [comment]
Good to know, then I suggest to either remove or update the plot here on GitHub, to avoid that misunderstanding again :)

Maybe using a plot using [plotly](https://plotly.com/julia/line-charts/) which is really nice in giving options to inspect data a bit closer with hovering and zooming.

[Cp_CO2.html](https://termo.us.to/public/Cp_CO2.html)

Regards!

**Comment by longemen3000** [comment]
after a long time, i finally found the bug. 
https://github.com/ClapeyronThermo/Clapeyron.jl/blob/af6570049a5e881f172abae51c4c64f2af38f89c/src/models/SAFT/SAFTVRSW/SAFTVRSW.jl#L214-L219
here, `σ[i]` should be `σ[i,i]`. It is fixed on the master branch.
