### ISSUE TITLE
SRK not reading critical temperature (Tc)

### ISSUE THREAD

**Issue by NicolasHeredia** [ClapeyronThermo/Clapeyron.jl#175]
Hello and thank you in advance.

I'm trying to create an SRK model with a custom database.

```julia
model_nh = SRK(["metanol", "benceno"]; userlocations=["database/"], alpha_userlocations = ["database/"])
```
And I did get:

cannot found any values for Tc.

Searching the SRK source code I found that the "userlocations" argument is not being passed to RK.
https://github.com/ClapeyronThermo/Clapeyron.jl/blob/4136658d31edbbfde794fbefd588024d9ddd79a2/src/models/cubic/RK/variants/SRK.jl

Could that be the problem?

**Comment by longemen3000** [comment]
yes, you are right!
in the meantime, you could use `RK(["metanol", "benceno"]; userlocations=["database/"], alpha = SoaveAlpha, alpha_userlocations = ["database/"])`

**Comment by pw0908** [comment]
Is this problem unique to SRK?

**Comment by longemen3000** [comment]
i remember doing a check a while ago for derived models, it seems that SRK just passed through the cracks

**Comment by pw0908** [comment]
QCPR might have that problem?

**Comment by longemen3000** [comment]
not directly, the userlocations got added here:
https://github.com/ClapeyronThermo/Clapeyron.jl/blob/4842741afc9b8308a19cfde515eb31df34022495/src/models/cubic/PR/variants/QCPR.jl#L26, but verbose was not considered

**Comment by pw0908** [comment]
Cool, so we can close this issue now

**Comment by NicolasHeredia** [comment]
Thank you for your answers
