### ISSUE TITLE
Error in unlike epsilon calculations - combining rules

### ISSUE THREAD

**Issue by michelevalsecchi** [ClapeyronThermo/Clapeyron.jl#179]
Hello,

I found that when using SAFT-gamma Mie and some unlike interaction energies are not specified the ones used by the code (found in model.params.epsilon.values) are not the correct ones given by the combining rule eps_ij = sqrt(eps_i*eps_j*sigma_i^3*sigma_j^3)/sigma_ij^3. See attached example with butane where epsilon_kl (CH3-CH2) is unspecified. Find also attached the zipped databank folder. I checked that the resulting calculations are off, but the errors disappear if I calculate the correct CR epsilon_ij and specify them in the databank.

What could be causing this? 
[SAFTgammaMie.zip](https://github.com/ClapeyronThermo/Clapeyron.jl/files/11455949/SAFTgammaMie.zip)
![Screenshot 2023-05-11 210105](https://github.com/ClapeyronThermo/Clapeyron.jl/assets/43810602/916a96ce-f2b7-47cb-ab9a-68cdb7b954f5)
Thank you in advance for the help!

**Comment by longemen3000** [comment]
hmm, i have to see this. the code that calculates all this is in these lines (`gc_sigma`):

https://github.com/ClapeyronThermo/Clapeyron.jl/blob/2afca1c08a500699293760239ffb7c67b9e12a2a/src/models/SAFT/SAFTgammaMie/SAFTgammaMie.jl#L98-L113

**Comment by pw0908** [comment]
I just double checked Haslam et al. (2008) where they formally derive the Hudson-McCoubrey combining rule and they do use the one we have implemented. Although, in the SAFT-gamma Mie paper, they use a slightly different version where they take a sqrt of the sigma terms as you have. I'd imagine that's something you'd have to check with the authors? 

We'll add both implementations to Clapeyron for now.

**Comment by michelevalsecchi** [comment]
Thank you both for the insight! @pw0908 In Lafitte et al. (2013) the form I highlighted comes from equating the unlike VDW constant of sutherland potentials \alpha_ij to berthelot rule on \alpha_i \alpha_j. Will the correct version be default now or should I specify it?

**Comment by longemen3000** [comment]
i think that we should set this as the default, what do you think @pw0908 ? we can add a `SAFTgammaMieMod` that uses the old behaviour

**Comment by longemen3000** [comment]
Closed in Clapeyron 0.4.11
