### ISSUE TITLE
Any plan to add SAFT fitting/regression function into package?

### ISSUE THREAD

**Issue by funkvps** [ClapeyronThermo/Clapeyron.jl#184]
Just as a discuss, Currently there lacks fitting/regression of SAFT params in opensource.

Is there a plan to add this, fitting/regression both the group parameter and also the association parameter.

BTW: this may also need implement the breakup method based on SMILES or other means to suggest the groups for a component.

**Comment by longemen3000** [comment]
We currently ship with an estimation framework: https://github.com/ClapeyronThermo/Clapeyron.jl/blob/master/examples/parameter_estimation.ipynb . Glad to hear about ideas or improvements to that framework.

> BTW: this may also need implement the breakup method based on SMILES or other means to suggest the groups for a component

We have a private repository that does that with `rdkit` (in beta for now).
