### ISSUE TITLE
EoS: (GC)-PPC-SAFT

### ISSUE THREAD

**Issue by longemen3000** [ClapeyronThermo/Clapeyron.jl#20]
@TheFranCouz this is an issue to track progress on a possible implementation of https://pubs.acs.org/doi/10.1021/acs.jced.6b00565 . feel free to comment

**Comment by MPE1991** [comment]
hi dear friend, can i have one of your social media accounts or your email to ask some question?

**Comment by longemen3000** [comment]
Hi, you can check some emails on the project.toml file https://github.com/ypaul21/Clapeyron.jl/blob/master/Project.toml

**Comment by pw0908** [comment]
There's also the Zulip chat linked on our main page!

**Comment by MPE1991** [comment]
> Hi, you can check some emails on the project.toml file https://github.com/ypaul21/Clapeyron.jl/blob/master/Project.toml

thank you so much

**Comment by MPE1991** [comment]
> There's also the Zulip chat linked on our main page!

unfortunately i couldn't find this tool.

**Comment by pw0908** [comment]
Just in case, you can contact me at pjwalker@caltech.com

I'll be updating the docs to include our email addresses.

**Comment by MPE1991** [comment]
many thanks dear friend

**Comment by longemen3000** [comment]
@pw0908 do we close this?

**Comment by pw0908** [comment]
We didn't implement this exact GC-PPCSAFT form, but I dont think we will?

**Comment by longemen3000** [comment]
i'm gonna close this, while we don't have that exact form of (GC)-PPC-SAFT, we do have GC-PCPSAFT.
