### ISSUE TITLE
Error when creating PPCSAFT models in new release

### ISSUE THREAD

**Issue by lucpaoli** [ClapeyronThermo/Clapeyron.jl#214]
The code:
```julia
using Clapeyron
model = PPCSAFT(["ethanol"])
```
throws the error:
```
ERROR: KeyError: key "b" not found
```
seemingly withing the `buildsites` function. Initial checks suggest this is only a problem for associating compounds, e.g. water / ethanol / methanol, while not cropping up for alkanes.

**Comment by longemen3000** [comment]
Really weird, I thought it was a typo in the db, but it is not

**Comment by longemen3000** [comment]
got the error fixed (with tests), waiting for said tests to finish to release a new version
