### ISSUE TITLE
Including Cp parameter along side Tm and ΔHfus for sle_solubility

### ISSUE THREAD

**Issue by samuel-zhang01** [ClapeyronThermo/Clapeyron.jl#222]
Dear developers of Clapeyron.jl,

When I was trying to reproduce literature values for PCSAFT sle_solubility plots, I came across the parameters needed to describe the solid phase interaction SolidHfus. I was wondering if the heat capacity term Cp is used at all in SolidHfus calculations. If not, is it possible to add an additional parameter to better model sle_solubility please?

```math
$$x_i^L=\frac{1}{\gamma_i^L}\exp\left[-\frac{\Delta h_{0i}^{SL}}{RT}\left(1-\frac{T}{T_{0i}^{SL}}\right)-\frac{\Delta c^{SL}_{P,0i}}{R}\left(\frac{T^{SL}_{0i}}{T}-1-\ln{\frac{T^{SL}_{0i}}{T}}\right)\right]$$
```
--> $\Delta c^{SL}_{P,0i}$

| Clapeyron Database File   |        |        |          |
|---------------------------|--------|--------|----------|
| SolidHfus Like Parameters |        |        |          |
| **species**               | **Mw** | **Tm** | **Hfus** |
| paracetamol2009             | 234.34 | 341.65 | 16090    |
| ...                       | ...    | ...    | ...      |

| Clapeyron Database File   |        |        |          |         |
|---------------------------|--------|--------|----------|----------|
| SolidHfus Like Parameters |        |        |          |         |
| **species**               | **Mw** | **Tm** | **Hfus** | **Cp**|
| paracetamol2009             | 234.34 | 341.65 | 16090    | xxx |
| ...                       | ...    | ...    | ...      | ... |

best,
Sam

**Comment by pw0908** [comment]
Hi Sam,

We can add this. My only issue is, from what I've seen in the literature is that, in some cases, `ΔcpLS` can be a function of temperature (even if the solid heat capacity is constant, the liquid heat capacity is definitely a function of temperature...). As such, do we need to account for this temperature dependence? Or is it good enough to approximate it as just being a constant.

Best,
Pierre

**Comment by pw0908** [comment]
@longemen3000 should we just added this as an additional parameter in `SolidHfus` that we can ignore?

**Comment by longemen3000** [comment]
seems a good addition to add to `SolidHfus`, ideally, we should have a way to specify a `Cpl(T)`, but adding this would be the first step towards that

**Comment by pw0908** [comment]
Cool; Ill quickly make that change before the next update

**Comment by pw0908** [comment]
This modification is now part of v0.5.7!
