### ISSUE TITLE
Data extraction from csv file

### ISSUE THREAD

**Issue by NaserHUB** [ClapeyronThermo/Clapeyron.jl#223]
Trying to plot data extracted from a csv file but faced with an error:
![image](https://github.com/ClapeyronThermo/Clapeyron.jl/assets/149005168/48797cfe-ce3c-434e-9855-4c02e773d16f)
![image](https://github.com/ClapeyronThermo/Clapeyron.jl/assets/149005168/710d0528-0140-4c60-83e0-e4d781d870a1)
![image](https://github.com/ClapeyronThermo/Clapeyron.jl/assets/149005168/2d674cf5-2b6b-48d0-856e-77e480e67498)

![image](https://github.com/ClapeyronThermo/Clapeyron.jl/assets/149005168/bbb56c7c-3ddc-46c4-8411-d89b54070886)
![image](https://github.com/ClapeyronThermo/Clapeyron.jl/assets/149005168/2735f418-71c5-4853-8321-7c62a36e8ab8)

help plz

**Comment by longemen3000** [comment]
The error seems in the plots, not in the library itself

**Comment by NaserHUB** [comment]
So what can be done in this case?

**Comment by pw0908** [comment]
Hi Naser,

Could you try `CSV.read("D2O_H2O_graphs.csv",Dataframe)` instead? That might return a dataframe that is easier to work with.

**Comment by NaserHUB** [comment]
all works now, thank you very much!
