### ISSUE TITLE
UNIFAC ether and aldehyde groups error

### ISSUE THREAD

**Issue by SalvadorBrandolin** [ClapeyronThermo/Clapeyron.jl#225]
Hello!

I found an error in the UNIFAC_like.csv file.

Both ether (CH-O) and aldehyde (CHO) groups are denoted as CHO. So if I want to model an aldehyde I get:

```julia
using Clapeyron

model = UNIFAC(["water",("acetaldehyde",["CH3"=>4, "CHO"=>1])])

model.params.R
```

I get in return:

SingleParam{Float64}("R") with 3 components:
 "H2O" => 1.7334
 "CH3" => 0.6325
 "CHO" => 1.1434

Being 1.1434 the R-value for the ether group and not the aldehyde.

Identifying the ether group as CH-O should fix it. ogUNIFAC and PSRK have the same problem.

**Comment by longemen3000** [comment]
Hmm, you are right, I'm gonna check the pair parameters if that error is present too

**Comment by longemen3000** [comment]
acording to http://www.aim.env.uea.ac.uk/aim/info/UNIFACgroups.html, HCO is the correct key for aldehyde, and CHO for ether

**Comment by SalvadorBrandolin** [comment]
Excellent!
