### ISSUE TITLE
EOS-CG 2021

### ISSUE THREAD

**Issue by pw0908** [ClapeyronThermo/Clapeyron.jl#233]
Multiparameter equation for CCS applications: https://link.springer.com/article/10.1007/s10765-023-03263-6

**Comment by ianhbell** [comment]
In that vein, you might want to also add the GERG-2008 model for natural gas. I just added it to teqp: https://github.com/usnistgov/teqp/pull/79

**Comment by longemen3000** [comment]
the GERG2008 was already added, it uses the same general infraestructure as the multiparameter fluids (with an addon for the difference in R)

**Comment by ianhbell** [comment]
@longemen3000 Ah cool, didn't realize that.

**Comment by longemen3000** [comment]
implemented in 0.5.11

**Comment by ianhbell** [comment]
Nice! Did you implement test values to be sure all the models are exactly the same?

**Comment by longemen3000** [comment]
Not yet,  I couldn't find test values of EOS-CG-2021 in the original paper. But on the code part, it just reuses the general `MultiFluid` code, so the only test necessary is that the data values stored in the database are correct 

On the data part, for the pure fluid, the fluids are taken from CoolProp JSONs or ported via REFPROP-interop. On the mixture models, I reused the existing ones where available (from EOS-LNG + some Coolprop mixture models), except the one with typos in the publication, that I have to extract from the paper itself(I have a function that generates mixture jsons from paper tables, so it is not completely manual).

**Comment by ianhbell** [comment]
One key point is to make sure that you are definitely, 100%, using the pure fluid models that are specified in the document.
