### ISSUE TITLE
Possible issue with bubble and dew point estimation (or SAFT-gamma Mie) 

### ISSUE THREAD

**Issue by Vtsoch** [ClapeyronThermo/Clapeyron.jl#262]
Hello, 

I hope you are all doing well. I am sorry, I have been having some troubles with reproducing some published results with SAFT-gamma Mie. I am not completely certain if there is an issue or if I am doing something silly, but so far I cannot see anything wrong with my code.  

Attached you can find a zip folder containing a Julia notebook with my estimates. 
[Clapeyron_SAFTgMie_estimates.zip](https://github.com/ClapeyronThermo/Clapeyron.jl/files/14517048/Clapeyron_SAFTgMie_estimates.zip)

It seems to me that in some cases bubble and dew point calculation does not work properly and Clapeyron values diverge from the published ones. In one interesting case (2-butanol + hexane) it seems that estimated dew points are actually the bubble points and vice versa.  

I hope you will be able to help me with this. Thank you!

**Comment by pw0908** [comment]
Hi Evangelos,

As far as I can see, there are only two main issues as you could reproduce most of the results (saturation curves, water+PZ, 2-butanol+hexane):
1. Bubble vs Dew points: from all your results, it looks like the dew and bubble points have been reversed. As far as I can tell, there might be a bit of a misunderstanding of how our bubble and dew point functions work. Taking bubble_temperature as an example, the input specify the conditions of the bubble point (the liquid phase composition and pressure at which the bubbles are just starting to appear) and the output is the corresponding composition of the vapour phase and temperature required to reach this bubble point. With that in mind, I believe you may have just mislabelled the curves?
2. MPZ+water: honestly, this one I have no clue what could be going wrong. I've double checked the parameters, convergence, the group assignments and everything that could have gone wrong. I had to make some minor changes to how you compare the chemical potential and pressure in the two phases and confirmed that they do indeed match. It could be possible that the developers mis-reported the parameters (the culprit appears to be cN)? You could try to confirm this by generate results for species which include the cN group. If you still cant reproduce the results, Id recommend getting touch with them. The only other thing that could be going wrong on our end is the association solver, but given you were able to reproduce the results for PZ, I'd be very surprised if that is the case...

Sorry that I can't be more helpful than saying you've been doing everything correctly, but we don't know what's going wrong.

@longemen3000 Any other ideas?

**Comment by Vtsoch** [comment]
Oh my goodness, yes, I obviously mislabelled the curves. Now, I noticed it. I am so sorry, that was so so silly of me. 

Please, do not apologise. Thank you very much for looking into it! 

Regarding the cN parameters, I think this might indeed be the case. I quickly tried to reproduce also water-EPZ results and there is again some divergence from the published values. Maybe some cN parameters have been mis-reported indeed. I am sorry, I was not able to look into in much today. I will doublecheck the results and I will test more systems (with and without the cN group). After I get some more estimates, I will contact someone from ICL. 
![water-EPZ](https://github.com/ClapeyronThermo/Clapeyron.jl/assets/138871142/54521bf6-7c85-44c2-b7b4-1a4cc169f262)
