### ISSUE TITLE
Issue with SAFT-VR-Mie models and water+alcohol

### ISSUE THREAD

**Issue by ianhbell** [ClapeyronThermo/Clapeyron.jl#282]
It seems the parameters were not implemented for all of the fluids in Dufal. At least I was not able to do:

```julia
using Clapeyron
vr15 = SAFTVRMie15(["water", "methanol"])
```
with a warning about missing parameters for sigma, which makes sense when I went into the files to try to find them they do not seem to be present.

Secondly (perhaps I should open a new issue, I can), I was unable to do bubble-point calculations with the older SAFT-VR-Mie model with water+ethanol at 1 bar:
```julia
using Clapeyron
vr15 = SAFTVRMie(["water", "ethanol"])
println(bubble_temperature(vr15, 1e5, [0.5, 0.5]))
```
and I get the error message:
```
ArgumentError: The interval [a,b] is not a bracketing interval.
You need f(a) and f(b) to have different signs (f(a) * f(b) < 0).
Consider a different bracket or try fzero(f, c) with an initial guess c.
```

**Comment by pw0908** [comment]
This is kind of an ironic pair of questions as they both have the inverse problem...

Yes, we are missing the methanol parameters (I'll add them to the database the next chance I get). However, you can still manually input them yourself.

The case with ethanol is the inverse where, while we do have parameters, they aren't correct... those are for the original Hard-Sphere kernel in the 2013 paper. I'll remove those. To my knowledge, there are no SAFT-VR Mir parameters (LJ kernel) for ethanol.

**Comment by ianhbell** [comment]
I think the methanol parameters in SAFT-VR-Mie-2015 might be incorrect as published in the paper of Dufal. I know there is a corrigendum, but this issue isn't mentioned there: https://doi.org/10.1080/00268976.2017.1402604. Might you know anything about that? I get this when I try to use the as-published parameters in teqp:

<img width="650" alt="image" src="https://github.com/user-attachments/assets/21803620-045c-4e3f-84a7-57fa1c8095fe">

but ammonia (and water) look perfect:

<img width="650" alt="image" src="https://github.com/user-attachments/assets/c94c284b-aea2-4310-858d-e7dfd3682398">

and I get exactly the right X_A for the water model, so the implementation seems ok:

<img width="650" alt="image" src="https://github.com/user-attachments/assets/a9f7e2db-855b-46e5-bc0f-1b421fdd1d31">

**Comment by ianhbell** [comment]
Thanks for the clarification about the OG SAFT-VR-Mie. Is that not these parameters from Lafitte:

<img width="650" alt="image" src="https://github.com/user-attachments/assets/c398d230-a334-497b-a613-b6a521fedb99">

**Comment by pw0908** [comment]
Regarding methanol: you are right, those parameters don't line up; Im finding the same on my end with our implementation. I haven't used the Mie kernel much (if at all) and, to my understanding, the MSE group has all but forgotten about it. If there is a discrepancy, it might be worth letting the eSAFT-VR Mie folks know as they are the only remaining users of the Mie kernel...

The only mistake I remember, which probably isn't related to this, is the definition of the reduced density in the I_ijab correlation. There was a back-and-forth about whether to use the segment-based or molecular-based reduced density. I believe the correct answer was to use the segment-based version, and our implementation definitely follows that. It would explain why methanol, being the only non-spherical species, is the only one failing.

Regarding ethanol: yup, those are the parameters we used. They will only work for the hard-sphere kernel.

**Comment by ianhbell** [comment]
Who might I contact about eSAFT-VR that might be interested?

Do you think the explanation for the discrepancy has to do with the definition of the reduced density in I_ijab?

Regarding ethanol+water: is it expected that the VLE calculations fail? Or is that just down to _mixture calculations are hard_?

**Comment by pw0908** [comment]
For eSAFT-VR Mie, the DTU folks are doing a lot of work with it.

The explanation I gave mist be responsible, but I'm not sure as I would think this would have been resolved.

For ethanol+water: It more so has to do with the bonding volume being 30 orders of magnitude too large:
```jullia
julia> model = SAFTVRMie(["water","ethanol"])
SAFTVRMie{BasicIdeal, Float64} with 2 components:
 "water"
 "ethanol"
Contains parameters: Mw, segment, sigma, lambda_a, lambda_r, epsilon, epsilon_assoc, bondvol

julia> model.params.bondvol
AssocParam{Float64}["water", "ethanol"]) with 2 values:
("water", "e") >=< ("water", "H"): 1.0169e-28
("ethanol", "e") >=< ("ethanol", "H"): 0.34558
```

**Comment by ianhbell** [comment]
Well, 30 orders of magnitude isn't too many :)

**Comment by pw0908** [comment]
SAFT-gamma Mie handles water+ethanol just fine:
```julia
julia> model = SAFTgammaMie(["water","ethanol"])
SAFTgammaMie{BasicIdeal} with 2 components:
 "water": "H2O" => 1
 "ethanol": "CH2OH" => 1, "CH3" => 1
Group Type: SAFTgammaMie
Contains parameters: segment, shapefactor, lambda_a, lambda_r, sigma, epsilon, epsilon_assoc, bondvol

julia> bubble_temperature(model,1e5,[0.5,0.5])
(359.13726269826776, 3.917183913834421e-5, 0.0285613827750914, [0.3591358480836402, 0.6408641519163598])
```

**Comment by ianhbell** [comment]
How about water + methanol with SAFTgammaMie?

**Comment by pw0908** [comment]
That was one of our early benchmarks to confirm our implementation was working:
```julia
julia> model = SAFTgammaMie(["water","methanol"])
SAFTgammaMie{BasicIdeal} with 2 components:
 "water": "H2O" => 1
 "methanol": "CH3OH" => 1
Group Type: SAFTgammaMie
Contains parameters: segment, shapefactor, lambda_a, lambda_r, sigma, epsilon, epsilon_assoc, bondvol

julia> bubble_temperature(model,1e5,[0.5,0.5])
(346.36959052202064, 3.0402270121400055e-5, 0.027499268084855713, [0.21813370834078877, 0.7818662916592112])
```

**Comment by ianhbell** [comment]
Cool so we will skip SAFT-VR-Mie for water+methanol. I guess we can close the issue, although the problem is not entirely solved for methanol but that's not Clapeyron's problem

**Comment by ianhbell** [comment]
I should really implement SAFT-Gamma-Mie one of these days. SAFT-VR-Mie was scary enough...
