### ISSUE TITLE
Derivation for `X_exact1`

### ISSUE THREAD

**Issue by ianhbell** [ClapeyronThermo/Clapeyron.jl#283]
Is there a reference I can read to see how to re-derive this:
https://github.com/ClapeyronThermo/Clapeyron.jl/blob/494a75e8a2093a4b48ca54b872ff77428a780bb6/src/models/SAFT/association.jl#L463 ?

@pw0908 You mentioned it came from the mass balance, something like this: 
<img width="545" alt="image" src="https://github.com/user-attachments/assets/3141cc52-a894-404e-9161-aa4d75ff2f68">
but I was hoping for a bit more guidance. I am confused because in Huang and Radosz the explicit solution depends on which interactions are allowed. E.g.:

<img width="718" alt="image" src="https://github.com/user-attachments/assets/fbe2a465-43f3-4ae2-860f-8cfe84a74e02">

**Comment by pw0908** [comment]
If you work through the maths, you can generalise the solution. 

Didn't I derive this in one of our discussions?

**Comment by longemen3000** [comment]
when i wrote that code, i did something like:
```
Xia = 1 + N_A*ρ*zj*njb*Δ
Xjb = 1 + N_A*ρ*zi*nia*Δ
```
and then solved for `Xia`. there is one specific case where `zi == zj & ni == nj` that corresponds to self-site association

**Comment by ianhbell** [comment]
Ah the discussion is here: https://github.com/ClapeyronThermo/Clapeyron.jl/discussions/260#discussioncomment-10142073. I looked in issues in Clapeyron and teqp but not in discussions. Thanks for the link

**Comment by ianhbell** [comment]
Sorry for the noise

**Comment by longemen3000** [comment]
check doi.org/10.1021/ie980206x for some extra work about binaries. I did obtain the general binary component solution in maxima, but it seems that michelsen method is faster than the evaluation of the polynomial coefficients.

**Comment by ianhbell** [comment]
I could believe that. You can also solve via an Eigenvalue solve, but that is also quite slow, and I am sure that Michelsen is faster
