### ISSUE TITLE
Adding fluid R1234ze(E) -  ReidIdeal

### ISSUE THREAD

**Issue by Sush1090** [ClapeyronThermo/Clapeyron.jl#292]
Hello, 

I am interested in adding R1234ze(E) refrigerant in the `ReidIdeal` model.  
The `IdealModel` implementation exists already. 

Would you know from where I can get the coefficients and add it in the CSV file?  
I am not sure that the paper suggested for CoolProp  [here](https://link.springer.com/article/10.1007/s10765-016-2040-6) suffices for this implementation. 

Thanking you 
Sushrut

**Comment by longemen3000** [comment]
i think that the best way to do this is to just fit the coefficients from the empiric model. you can access such empiric model in the following way:
```
using CoolProp #loads CoolProp csv files
ref_ideal = EmpiricIdeal("R1234ze(E)")
```

**Comment by longemen3000** [comment]
i did something like this:
```
using CoolProp #loads CoolProp csv files
ref_ideal = EmpiricIdeal("R1234ze(E)")
n = 200
T = LinRange(169,420,n) #according to the paper, the reference model is valid from 169 to 420 K
Cp = Clapeyron.VT_isobaric_heat_capacity.(ref_ideal,1,T) #this function is independent of volume
H = hcat(ones(n),T,T.^2,T .^3,T .^4)
coeffs = H\Cp
```

**Comment by Sush1090** [comment]
@longemen3000 Thank you.  This is very efficient.
There is one small point -  there should be a discontinuity around 250 - 300K as that is the saturation temperature  at 101325Pa (depending on the EoS). This is also visible in the `IdealModel`.  Here is the example

![image](https://github.com/user-attachments/assets/c58f44c0-22e8-44e0-83d0-ddfa423c40f9)

With the polynomial it is not possible. Possibly there is some additional adjustment needed.  I do not know how much it will affect the computation of other properties. 

Thanking you,
Sushrut

**Comment by longemen3000** [comment]
hmm, i do not see such discontinuity in the ideal model itself, are you sure are you calling the ideal model and not the full model?. in theory, a ideal gas model should not have any information about equilibria.

**Comment by longemen3000** [comment]
for example this plot has the full model in addition to the ideal one:
![image](https://github.com/user-attachments/assets/b6b29dd4-f4c7-41f3-86a0-d5a46483b516)

**Comment by Sush1090** [comment]
Ah yes indeed. I was using the full model. 
Thank you.

**Comment by Sush1090** [comment]
This is doing exactly what I was hoping for :)
