### ISSUE TITLE
index_reduction small bug -- eps(::Type{Int64})

### ISSUE THREAD

**Issue by Sush1090** [ClapeyronThermo/Clapeyron.jl#294]
Hello,
I have the following code:
```
julia> using Clapeyron

julia> model = cPR(["toluene","water"],idealmodel = ReidIdeal);

julia> crit_mix(model,[1,1])
```

I get the following error:

```
ERROR: MethodError: no method matching eps(::Type{Int64})

Closest candidates are:
  eps(::Type{Float64})
   @ Base float.jl:969
  eps(::Type{Float16})
   @ Base float.jl:967
  eps(::Type{Dates.Time})
   @ Dates C:\Users\sush9\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Dates\src\types.jl:434
  ...

Stacktrace:
 [1] index_reduction(model::PR{ReidIdeal, TwuAlpha, NoTranslation, vdW1fRule}, z::Vector{Int64})
   @ Clapeyron C:\Users\sush9\.julia\packages\Clapeyron\vnjPG\src\utils\index_reduction.jl:19
```

Seems like the function  `index_reduction` doesn't accept `Int` as vector input. It works well for all cases where `elttype` is not `Int`

Thanking you,
Sushrut

**Comment by Sush1090** [comment]
This is because it uses `eps` which doesn't accept `Int` values.

**Comment by pw0908** [comment]
Hi Sushrut,

This bug is mainly related to the fact that you used integers to define compositions. If you wanted to use `[1,1]`, you'd have to write `[1.,1.]`. However, since you're looking for the critical point, it's required that you define it as molar compositions (I.e. sums up to one). The following works:
```

julia> model = cPR(["water","toluene"])
PR{BasicIdeal, TwuAlpha, NoTranslation, vdW1fRule} with 2 components:
 "water"
 "toluene"
Contains parameters: a, b, Tc, Pc, Mw

julia> crit_mix(model,[0.5,0.5])
(575.0629608385639, 7.261867506677699e6, 0.00023413722405951902)
```

**Comment by Sush1090** [comment]
Yes indeed I figured that out just now :)

I'll close this issue.

Thank you
