### ISSUE TITLE
Query on Property Calculation in the Two-Phase Region

### ISSUE THREAD

**Issue by Sush1090** [ClapeyronThermo/Clapeyron.jl#303]
Hello,

I am currently working on computing bulk properties, such as density, volume, temperature, entropy, and specific heats (Cp, Cv), using enthalpy and pressure as inputs.

In most cases, my local solver finds the temperature via the `Tproperty` function and then computes the required property. This approach works well outside the two-phase region. However, I am looking for a robust method to handle calculations in the two-phase region as well.

Specifically, I am searching for a tool similar to `PropsSI` that computes properties accurately using pressure and enthalpy. Is such functionality available in Clapeyron, or is there a recommended method for handling this?

Your guidance would be greatly appreciated.

Thank you,
Sushrut

**Comment by longemen3000** [comment]
Hello,
technically, what you need is a T-H (T-S and T-V) flash. At the moment, we only have P-T flash implementations. I think we need to track this, is ok if we use this issue for that purpose?

**Comment by Sush1090** [comment]
Yes indeed :)

**Comment by longemen3000** [comment]
i think i got an idea on how to do this.
- on Clapeyron 0.6.5, i introduced some modules (`PT`,`PH`,`PS`,`VT`), the idea is to do something like:
```
VT.enthalpy(model,v,T,z) #equivalent to Clapeyron.VT_enthalpy(model,v,T,z)
PT.enthalpy(model,p,T,z) #equivalent to enthalpy(model,p,T,z)
PS.enthalpy(model,p,s,z) #equivalent to calling TProperty and then evaluating enthalpy at p,T conditions
```
the idea is to add flash functions in the following way
```
result = PT.flash(model,p,T,z) #equivalent to Clapeyron.tp_flash2(model,p,T,z), changing the output of tp_flash is breaking
comps,fractions,volumes,data = result #if you need specific data
hmix = enthalpy(model,result) #if you need to calculate a weighed sum of property for all phases, the "glide".
```
A good thing with `Tproperty` is that identifies equilibria conditions (when prop_bub < prop < prop_dew), so we can modify it to also return the condition (as you already saw in #309) Now, the idea is to hook an adequate flash for each pair of specifications, using the output of `Tproperty` as an starting point.

**Comment by longemen3000** [comment]
on the current master:
```
julia> model = cPR(["ethane","propane"],idealmodel=ReidIdeal)
PR{ReidIdeal, TwuAlpha, NoTranslation, vdW1fRule} with 2 components:
 "ethane"
 "propane"
Contains parameters: a, b, Tc, Pc, Mw

julia> p = 101325.0
101325.0

julia> h = -13831.0 #enthalpy at T = 0.5*T_bubble + 0.5*T_dew
-13831.0

julia> z = [0.5,0.5]
2-element Vector{Float64}:
 0.5
 0.5

julia> Clapeyron.ph_flash(model,p,h,z)
([[0.17317188972407677, 0.8268281102759232], [0.6229562865518485, 0.37704371344815146]], [0.4753594797398013, 0.5246405202601987], [6.610779468339207e-5, 0.017026792382129566], Clapeyron.PTFlashData{Float64}(101325.0, 213.38726377112155, -162.11074278396245))

julia> enthalpy(model,result)
-13830.999999999996
```

**Comment by Sush1090** [comment]
I get this error when running the script 
```julia
ERROR: UndefVarError: `spec` not defined in `Clapeyron`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] Clapeyron.FlashSpecifications(spec1::typeof(pressure), val1::Float64, spec2::typeof(enthalpy), val2::Float64)
   @ Clapeyron C:\Users\sush9\.julia\packages\Clapeyron\splf7\src\methods\property_solvers\multicomponent\flash.jl:133
```

I added the master branch using 
```julia
add https://github.com/ClapeyronThermo/Clapeyron.jl.git
```

status
```
[7c7805af] Clapeyron v0.6.5 `https://github.com/ClapeyronThermo/Clapeyron.jl.git#master`
```

**Comment by longemen3000** [comment]
huh, weird, it works in my REPL right now, let me check

**Comment by Sush1090** [comment]
This is actually amazing. This is very close to CoolProp or RefProp

**Comment by Sush1090** [comment]
There is a difference in your version or the version on the master branch? 
Because I cannot precompile it:
```julia
(ClapeyronFlash) pkg> precompile
Precompiling project...
  ✗ Clapeyron
  0 dependencies successfully precompiled in 5 seconds. 121 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

Clapeyron

Failed to precompile Clapeyron [7c7805af-46cc-48c9-995b-ed0ed2dc909a] to "C:\\Users\\sush9\\.julia\\compiled\\v1.11\\Clapeyron\\jl_CD2A.tmp".
ERROR: LoadError: UndefVarError: `helmholtz_energy` not defined in `Clapeyron`
Stacktrace:
  [1] top-level scope
    @ C:\Users\sush9\.julia\packages\Clapeyron\GVLnz\src\methods\property_solvers\multicomponent\flash.jl:212
```

**Comment by longemen3000** [comment]
yes, fixing that right now

**Comment by Sush1090** [comment]
It works! thank you

**Comment by Sush1090** [comment]
Can we close this issue?

**Comment by longemen3000** [comment]
This needs a release and a lot of polish, so not now.

**Comment by longemen3000** [comment]
releasing 0.6.6 now, so i'm gonna close this for now. Feel free to reopen if something occurs.
