### ISSUE TITLE
Question: ModelingToolKit and Clapeyron

### ISSUE THREAD

**Issue by branch171** [ClapeyronThermo/Clapeyron.jl#311]
Has anyone successfully used Clapeyron within ModelingToolKit for thermodynamic properties. 

I am struggling to call Clapeyron functions like mass_density, enthalpy or Tproperty. 

To use them I use:

function h_pT(model,p,T,z)
    return enthalpy(model,p,T,z)
end
@register_symbolic h_pT(model::EoSModel,p::Float64,T::Float64,z::Vector{Float64})

However, as soon as the variables inside are variables used by ModelingToolKit and not parameters or function inputs all fails.  

Any examples of success out there?

**Comment by branch171** [comment]
Hope this helps someone

**Comment by pw0908** [comment]
This might be of interest to you: https://github.com/SciML/ProcessSimulator.jl

They’re building a process simulator with Clapeyron as a backend.

**Comment by Sush1090** [comment]
> I am struggling to call Clapeyron functions like mass_density, enthalpy or Tproperty.

For `Tproperty` I do as follows:

```julia
Tproperty_S(model::EoSModel,p,s,z) = Clapeyron.Tproperty(model::EoSModel,p,s,z,entropy,phase = "unkown")
@register_symbolic Tproperty_S(model::EoSModel,p,s,z)
```
I separately register `Tproperty` for the specific function I want to solve. Else sometimes it does not register correctly with the internals of Clapeyron.
