### ISSUE TITLE
Problem with reproducing Figure 9 in "Ind. Eng. Chem. Res. 2002, 41, 5510-5515"

### ISSUE THREAD

**Issue by jiarongsang** [ClapeyronThermo/Clapeyron.jl#313]
I cannot reproduce Figure 9 in "Ind. Eng. Chem. Res., Vol. 41, No. 22, 2002". Below is my code:
using Clapeyron
model = PCSAFT(["methanol","1-octanol"])
p=1.013e5
nnn=99
x = range(0.01,0.99,length=nnn)
X = Clapeyron.FractionVector.(x)
y = []
T = []
v_l = []
v_v = []
bub = []
v0 =[]
    for j ∈ 1:nnn
        if j==1
            append!(bub, [bubble_temperature(model,p,X[j])])
            v0 = [bub[j][1],log10(bub[j][2]),log10(bub[j][3]),bub[j][4][1],bub[j][4][2]]
        else
            append!(bub, [bubble_temperature(model,p,X[j];v0=v0)])
            v0 = [bub[j][1],log10(bub[j][2]),log10(bub[j][3]),bub[j][4][1],bub[j][4][2]]
        end
    end

**Comment by pw0908** [comment]
You might need to use an association combining rule:
```julia
model = PCSAFT(["methanol","1-octanol"]; assoc_options=AssocOptions(combining=:elliott))
```
There might also be a binary interaction parameter which I'm not aware of.

@longemen3000 do you remember which combining rule the original PC-SAFT used for association?

**Comment by jiarongsang** [comment]
Thank you very much, association combining rule is needed :)

**Comment by longemen3000** [comment]
about the binary interaction parameter, table 2 of that paper has a coefficient kij for methanol/1-octanol of 0.02. you can try using:
```julia
model = PCSAFT(["methanol","1-octanol"]; assoc_options=AssocOptions(combining=:elliott))
Clapeyron.set_k!(model,[0.0 0.02; 0.02 0.0]])
``
the paper mentioned in the issue is the first use of the PCSAFT EoS with association, and they use elliott's combining rule there. https://pubs.acs.org/doi/abs/10.1021/ie010954d

**Comment by pw0908** [comment]
@jiarongsang Were you able to reproduce the figure?

**Comment by jiarongsang** [comment]
Yes, thank you for your help @pw0908 and @longemen3000.
