### ISSUE TITLE
On implementing all three flash algorithms and performance enhancements

### ISSUE THREAD

**Issue by abcdvvvv** [ClapeyronThermo/Clapeyron.jl#314]
I have developed a simple process simulator, the basic framework is okay but only three modules with the PR equation in it now. I didn't notice the Clapeyron.jl until the last few days, so I would like to interface my simulator with this package for further development. Therefore, I would like to discuss here with you the possibility of implementing all three flash evaporation in Clapeyron: TPflash, vfPflash (vf=vapor fraction because I reserve V for volume) and QPflash.

1. about the performance of tpflash
I noticed that Clapeyron has implemented [tpflash](https://clapeyronthermo.github.io/Clapeyron.jl/dev/properties/multi/#TP-Flash), and provides at least four different flash algorithms. However there seems to be a significant performance gap between it and MultiComponentFlash, I tried a simple case:
```julia
using Clapeyron, BenchmarkTools
model = PR(["IsoButane", "n-Butane", "n-Pentane", "n-Hexane"]);
z = fill(1/4, 4)
@btime tp_flash($model, 1e5, 303.15, $z, DETPFlash())
# more than 2 minutes
@btime tp_flash($model, 1e5, 303.15, $z, RRTPFlash())
# 27.900 μs (512 allocations: 45.33 KiB)
@btime tp_flash($model, 1e5, 303.15, $z, MichelsenTPFlash())
# 25.700 μs (467 allocations: 40.75 KiB)
@btime tp_flash($model, 1e5, 303.15, $z, MultiPhaseTPFlash())
# 254.000 μs (7282 allocations: 503.06 KiB)
```
Do you have any clues about the interface to MultiComponentFlash (MCF) provided by Clapeyron being slower than MCF itself? Maybe adding some buffers would make it faster, but I'm new to this package and I'm not really sure. Beside, when calling MCF's directly its performance is excellent:
```julia
using MultiComponentFlash, BenchmarkTools
props = MolecularProperty.(["IsoButane", "n-Butane", "n-Pentane", "n-Hexane"])
mixture = MultiComponentMixture(props)
eos = GenericCubicEOS(mixture, PengRobinson())
conditions = (p=1e5, T=303.15, z=fill(1/4, 4))
# Perform a flash to get the vapor fraction
@btime flash_2ph($eos, $conditions, verbose=false)
# 4.457 μs (38 allocations: 2.92 KiB)
```
However, MCF now only supports cubic EOS, and for polar systems we would like to model the simulation with activity coefficients to provide more accurate results. So, is there room to further improve the performance of the code?
E.g. provide some buffers for tp_flash_michelsen function to reduce memory allocation; implement solving for Jacobian matrices by some hand writing code and use it instead of ```ForwardDiff.jacobian!(J,f!,F,x,config)``` (line 390 in general_flash.jl). Because ForwardDiff can be time consuming.

2. Here are some of my basic thoughts on vfPflash. Its easy to implement, just need to solve for a single variable temperature using the secant method. Is it possible to add vfpflash to clapeyron in the future?
```julia
function nestvfP!(t, (p, vf, x, y, z, K))
    k_max = 50
    K2 = similar(K)
    for k = 1:k_max
	rachford_rice!(t, p, vf, x, y, z, K2)
	r = norm(K2 .- K)
	copy!(K, K2)
	r < 1e-5 && break
	k == k_max && error("k=$k, nested vfPflash not converge.")
    end
    return sum(y) - sum(x)
end

function rachford_rice!(t, p, vf, x, y, z, K)
    x ./= sum(x)
    y ./= sum(y)
    lnϕx, _ = Clapeyron.lnϕ(mixture, p, t, x; phase=:l)
    lnϕy, _ = Clapeyron.lnϕ(mixture, p, t, y; phase=:v)
    @. K = exp(lnϕx - lnϕy)
    @. x = z / (vf * (K - 1) + 1)
    @. y = x * K
    return sum(y) - sum(x)
end

itervfP!(t, (p, vf, x, y, z, K)) = rachford_rice!(t, p, vf, x, y, z, K)

function vfPflash(vf, p, z::AbstractVector;
    t0=NaN,
    K0=Float64[],
    flashAlgo=:successive_substition,
    xatol=1e-7,
    atol=1e-7)

    # This function needs to be solved over a wide range of t. Other functions need to be allowed to provide an initial guess (t0) for temperature, or if this is not provided, a method for estimating the initial temperature needs to be implemented. The simplest normal boiling point * molar fraction is used here.
    isnan(t0) && (t0 = dot(z, ScalarProps.Tb))
    # Again, other functions are allowed to provide the initial K as K0, otherwise an estimate needs to be provided.
    isempty(K0) && (K0 = provide_ini_K(t0, p))
    nc = length(z)
    x = Vector{Float64}(undef, nc)
    y = Vector{Float64}(undef, nc)
    K = K0

    if flashAlgo == :nested
        @. x = z / (vf * (K - 1) + 1)
        @. y = K * x
        # In this nested approach, the K is iterated until convergence inside the loop and the scalar t is solved externally by the secant method.
        t = secant(nestvfP!, t0, (p, vf, x, y, z, K); lb=0.1, ub=1000.0, xatol, atol)

    elseif flashAlgo == :successive_substition
        @. x = z / (vf * (K - 1) + 1)
        @. y = K * x
        t = t0
        # Iterate using the fixed point method inside the loop and the secant method on the outside.
        t = secant(itervfP!, t, (p, vf, x, y, z, K); lb=0.1, ub=1000.0, xatol, atol)

    elseif flashAlgo == :newton
        # Use Newton's method to simultaneously solve for t and K
    end

    return t, K
end
```
QPflash, however, solves for the temperature, vapor fraction, and K-value of a mixture when its real enthalpy and pressure are known. We can continue the discussion if you are interested.

**Comment by pw0908** [comment]
Hi @abcdvvvv, we actually have a lot of interest in implementing all of the other flashes. In fact, @longemen3000 has done a lot of work towards adding the p-H, p-S, etc flashes. I’ll just comment on a few things:
1. MutliComponentFlash is a very optimised for cubics-only flash algorithm. Our implementations are meant to handle the vast array of models available. That being said, there are probably plenty of ways our methods could be optimised.
2. It may be of interest to you that we are collaborating with the folks at SciML on developing a process simulator with Clapeyron: https://github.com/SciML/ProcessSimulator.jl. You may want to contact them about getting involved in this work.

**Comment by longemen3000** [comment]
On the master branch, there is a general xy_flash algorithm, based on the unified formulation of Ben gharbia (2021). 

A vapor fraction - pressure flash can be expressed in terms of this formulation, but as you said, the initial point is the problem.

At the moment we are using the rigorous starting point approach (the temperature should be between the bubble and dew), but im looking for other starting points (you can also provide your own, that would skip the initialization).

**Comment by longemen3000** [comment]
On performance, you can provide caches for some functions, but one problem is that the calculation of fugacity coefficients is done via AD, vs MCF that does it manually. 

There is also a design decision we took with our cubics (evaluate alpha functions n times and store the results in a vector) vs the design decision that MCF took (evaluate alphas n^2 times). Probably mixing the two approaches is better in this particular case.

With that said, there are a lot of performance improvements that need to be done on the michelsen flash (and RR flash, they use the same function, check `tp_flash/MichelsenTPFlash.jl` and `tp_flash/michelsen_base.jl`).

**Comment by longemen3000** [comment]
One thing i'm really interested, is if we can provide a general successive substitution step (multicomponent-multiphase). On limited testing, the current non linear system formulation seems pretty robust to the initial point, but one cannot be sure. The SS step in `MultiphaseTPFlash` is done by solving the multidimensional RR problem and then updating the compositions, but for a general formulation, there is a need to update two additional specifications on each step.

I added some modifications to the general flash algorithm so vfP and vfT flashes are supported. for example, we can do a flash at T = 208.0 K

```julia-repl
julia> model = cPR(["ethane","propane"],idealmodel=ReidIdeal)
PR{ReidIdeal, TwuAlpha, NoTranslation, vdW1fRule} with 2 components:
 "ethane"
 "propane"
Contains parameters: a, b, Tc, Pc, Mw

julia> h = -13831.0 #enthalpy at T = 0.5*T_bubble + 0.5*T_dew
-13831.0

julia> p = 101325.0
101325.0

julia> z = [0.5,0.5]
2-element Vector{Float64}:
 0.5
 0.5

julia> r = Clapeyron.ph_flash(model,p,h,z) #initial point
Flash result at T = 208.591, p = 101325.0 with 2 phases:
 (x = [0.2441, 0.7559], β = 0.475595, v = 6.44863e-5)
 (x = [0.732082, 0.267918], β = 0.524405, v = 0.0166522)

julia> spec = Clapeyron.FlashSpecifications(Clapeyron.Vfrac(2),0.5,Clapeyron.temperature,208.0) #specifications struct
Clapeyron.FlashSpecifications{Clapeyron.Vfrac, Float64, typeof(Clapeyron.temperature), Float64}(Clapeyron.Vfrac(2), 0.5, Clapeyron.temperature, 208.0)

julia> Clapeyron.xy_flash(model,spec,z,r)
Flash result at T = 208.0, p = 1.01635e5 with 2 phases:
 (x = [0.254992, 0.745008], β = 0.5, v = 6.42564e-5)
 (x = [0.745008, 0.254992], β = 0.5, v = 0.0165538)
```

or a flash a p = 120000.0:
```
julia> spec = Clapeyron.FlashSpecifications(Clapeyron.Vfrac(2),0.5,pressure,120000.0)
Clapeyron.FlashSpecifications{Clapeyron.Vfrac, Float64, typeof(pressure), Float64}(Clapeyron.Vfrac(2), 0.5, pressure, 120000.0)

julia> Clapeyron.xy_flash(model,spec,z,r)
Flash result at T = 211.497, p = 120000.0 with 2 phases:
 (x = [0.260385, 0.739615], β = 0.5, v = 6.46203e-5)
 (x = [0.739615, 0.260385], β = 0.5, v = 0.0142007)
```

For the initial point, we have the (currently unexported) functions `extended_saturation_pressure` and `extended_saturation_temperature`, that calculate the saturation points if the condition is subcritical, or calculate an extrapolation based on the dp/dT at the critical point otherwise.

**Comment by abcdvvvv** [comment]
I'm surprised you've modified the generic flash algorithm to make it support vfp and vfT in such a short period of time. I'm not quite sure how to provide a provide a general successive substitution step, as my research on flash is not as exhaustive as yours.

I still tried your code with the same mixture as before, but lines 7 and 10 report the same error:
```julia
model = PR(["IsoButane", "n-Butane", "n-Pentane", "n-Hexane"]);
z = [0.25, 0.25, 0.25, 0.25]
p = 1e5
h = enthalpy(model, 1e5, 303.15, z)
@show r = Clapeyron.ph_flash(model, p, h, z)
spec = Clapeyron.FlashSpecifications(Clapeyron.Vfrac(2), 0.5, Clapeyron.temperature, 308.0)
@show Clapeyron.xy_flash(model, spec, z, r) # line 7

spec = Clapeyron.FlashSpecifications(Clapeyron.Vfrac(2),0.5,pressure,120000.0)
@show Clapeyron.xy_flash(model, spec, z, r) # line 10
```
```julia
ERROR: BoundsError: attempt to access 1-element view(::Vector{Float64}, 6:6) with eltype Float64 at index [2]
Stacktrace:
  [1] throw_boundserror(A::SubArray{Float64, 1, Vector{Float64}, Tuple{UnitRange{Int64}}, true}, I::Tuple{Int64})
    @ Base .\abstractarray.jl:737
  [2] checkbounds
    @ .\abstractarray.jl:702 [inlined]
  [3] getindex
    @ .\subarray.jl:322 [inlined]
  [4] xy_flash_neq(output::Vector{…}, model::PR{…}, zbulk::Vector{…}, np::Int64, input::Vector{…}, state::Clapeyron.FlashSpecifications{…})
    @ Clapeyron d:\Julia-Packages\Clapeyron.jl\src\methods\property_solvers\multicomponent\flash\general_flash.jl:309        
  [5] f!
    @ d:\Julia-Packages\Clapeyron.jl\src\methods\property_solvers\multicomponent\flash\general_flash.jl:394 [inlined]        
  [6] xy_flash(model::PR{…}, spec::Clapeyron.FlashSpecifications{…}, z::Vector{…}, comps0::Vector{…}, β0::Vector{…}, volumes0::Vector{…}, T0::Float64; rtol::Float64, atol::Float64, max_iters::Int64)
    @ Clapeyron d:\Julia-Packages\Clapeyron.jl\src\methods\property_solvers\multicomponent\flash\general_flash.jl:402        
  [7] xy_flash
    @ d:\Julia-Packages\Clapeyron.jl\src\methods\property_solvers\multicomponent\flash\general_flash.jl:353 [inlined]        
  [8] xy_flash(model::PR{…}, spec::Clapeyron.FlashSpecifications{…}, z::Vector{…}, flash::Clapeyron.FlashResult{…})
    @ Clapeyron d:\Julia-Packages\Clapeyron.jl\src\methods\property_solvers\multicomponent\flash\general_flash.jl:350        
  [9] macro expansion
    @ show.jl:1181 [inlined]
 [10] top-level scope
```

**Comment by longemen3000** [comment]
the main error occurs because the result of `ph_flash` returns only one phase. a better error can be thrown there.

**Comment by abcdvvvv** [comment]
hi @longemen3000 , thanks for your reply. I've been idle lately so I'm going to take a look at how these flash algorithms are implemented. I would like to help improve the performance if possible.
I have encountered two new problems with this mixture still. The first one is that I'd like to know why this mixture has such a drastic change in volume and enthalpy at 297.23 and 297.24 K.
```julia
model = PR(["IsoButane", "n-Butane", "n-Pentane", "n-Hexane"]);
z = [0.25, 0.25, 0.25, 0.25]
p = 1e5
bubble_temperature(model, 1e5, z) # 282.28
dew_temperature(model, 1e5, z) # 312.93
vol = volume(model, 1e5, 297.23, z) # 0.00010937486317401194
vol = volume(model, 1e5, 297.24, z) # 0.02376886872815413
h = enthalpy(model, 1e5, 297.23, z) # -18735.675614649736
h = enthalpy(model, 1e5, 297.24, z) # 5926.929243088876
```

The second one is, doesn't tp_flash use the DETPFlash method by default, so why does the calculation result differ from specifying ```DETPFlash()``` when I don't enter the optional arguments? 
```julia
_, n, _ = tp_flash(model, p, 284.4, z) # works for 284.5, but wrong answer for 284.4 K
# ([0.25 0.25 0.25 0.25], [0.25 0.25 0.25 0.25], -6.614840627297242)
_, n, _ = tp_flash(model, p, 284.4, z, DETPFlash())
vf = sum(n[2, :]) / sum(n) # 0.10143226379951037
_, n, _ = tp_flash(model, p, 284.4, z, RRTPFlash()) 
vf = sum(n[2, :]) / sum(n) # 0.10143251126359516
```

**Comment by longemen3000** [comment]
answering the first question,when you do `property(model,p,T,z)`, you are implicitly doing:
```
V = volume(model,p,T,z;kwargs....)
VT.property(model,V,T,z)
```
the determination of volume roots is done by calculating which root has the lowest gibbs energy. you can force the calculation to give you any root by passing the `phase` keyword:
```
vol1 = volume(model, 1e5, 297.23, z) #0.00010937486317401194, liquid volume
vol2 = volume(model, 1e5, 297.24, z) #0.02376886872815413, gas volume
vol1_specified = volume(model, 1e5, 297.24, z,phase = :l)# 0.00010937680330555043
vol2_specified = volume(model, 1e5, 297.23, z,phase = :v)#0.02376798143986181
```
The change of phase explains the changes in enthalpy. 
The error in `isstable` seems genuine, but it is also a typo in the documentation. `isstable` checks (p,T,z) pairs, the function that checks (V,T,z) pairs is `Clapeyron.VT_isstable`.

On the flash method, i think it defaults to `MultiPhaseTPFlash()`, the algorithm to decide which flash method is here (for general EoS, some restricted EoS only support rachford -rice):
https://github.com/ClapeyronThermo/Clapeyron.jl/blob/36ce02eb09e7d0ef3cb6a7ba821384874b67fa75/src/methods/property_solvers/multicomponent/flash/PT.jl#L42-L59
the fact that `MultiPhaseTPFlash` fails for that combination of inputs is a bug in the algorithm. the resulting bug was that the checks were too strict at the start, it is fixed in the latest master.
