### ISSUE TITLE
Precompiling Clapeyron (cache misses: wrong source (1))

### ISSUE THREAD

**Issue by jamiecripwell** [ClapeyronThermo/Clapeyron.jl#321]
Hi there

It's been a while since I used the package, but today after updating Julia from V1.8 to the most recent V1.11.2, I get the above Info message, followed by a LoadError regarding the PackedVectorsOfVectors package being missing, and which also includes a "failed to precompile Clapeyron to [my Julia directory].

I have tried removing and readding both the PackedVectorsOfVectors package and Clapeyron itself, I've re-forked the repository in the hope of "starting fresh", but the error persists.

I'm not the most proficient with these "backend management" skills, so please forgive any ignorance that I'm showing, but I would really appreciate any assitance sorting this out.

Thanks!

**Comment by pw0908** [comment]
Hi Jaime,

Seems like you’ve sorted it out? I’ll just mention a probably unrelated issue with the newer Julia versions is that compilation seems to be a lot slower, especially with 1.11 and above. I personally use the last stable version of Julia (1.10.6). 

Best regards,

Pierre
