### ISSUE TITLE
Just a question, not an issue

### ISSUE THREAD

**Issue by BradenDKelly** [ClapeyronThermo/Clapeyron.jl#48]
I am just curious what the roadmap is for flash calculations? Will you be implementing such things as the Tangent Plane Criteria etc and essentially solve for the number of possible phases automatically? Do you need or want help?

**Comment by pw0908** [comment]
Hi Braden,

That's more than any of us! If you can translate your code to Julia, we can refine it over time to get at least a working implementation.

I agree that the flash algorithm is something that's very useful in any thermo modelling software and it's been a gap in our packages we've been meaning to fill for a while...

It's amazing that you had to code it for a course! I'm guessing this was at the DTU? 

Best regards,

Pierre
