### ISSUE TITLE
Structured SAFT gamma Mie

### ISSUE THREAD

**Issue by pw0908** [ClapeyronThermo/Clapeyron.jl#84]
Cool extension of SAFT gamma mie which accounts for the structure of the molecule: 
- Alkanes: https://aip.scitation.org/doi/10.1063/5.0048315
- Alcohols: https://pubs.acs.org/doi/abs/10.1021/acs.iecr.2c00198

It's a bit weird that it's only comparable to regular SAFT-gamma Mie (probably an indication of the limitations of the underlying theory). But would be interesting to see if Clapeyron can handle this input type.

**Comment by longemen3000** [comment]
with a quick glance at the original paper, i think that pair structure can be represented by an interaction matrix for each term, something like a `SingleParam{Matrix{Float64}}`

**Comment by longemen3000** [comment]
one problem is that the size of the interaction matrix is group and component dependent. hmm, maybe we need a new type of parameter capable of expressing this relationship

**Comment by pw0908** [comment]
Could just be a user-defined input where we have a check in the constructor that the size is consistent
