### ISSUE TITLE
Ammonia Multifluid

### ISSUE THREAD

**Issue by longemen3000** [ClapeyronThermo/Clapeyron.jl#85]
https://doi.org/10.1016/j.fluid.2020.112496
https://doi.org/10.1016/j.fluid.2020.112749 (corrigendum)

Basically, a GERG2008-like model for fluids containing ammonia and related mixtures.

**Comment by pw0908** [comment]
Interesting; seems like it should be quite quick to implement into Clapeyron?

It also covers a lot of funky species which is kinda neat!

**Comment by ianhbell** [comment]
Yes, this model is not too complicated to implement, similar to existing multi-parameter empirical EOS, aside from the new term. It is implemented in teqp and CoolProp

**Comment by ianhbell** [comment]
The EOS has been published: https://aip.scitation.org/doi/abs/10.1063/5.0128269

The SI includes implementation, and it is also already in teqp.
